name: React front-end test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      working-directory: frontend
      run: npm ci

    - name: Build
      working-directory: frontend
      run: npm run build --if-present
