name: NPM Start

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      working-directory: frontend
      run: npm ci

    - name: Build and run
      working-directory: frontend
      run: |
        npm run build
        npm start
